### ISSUE TITLE
S3: Reverse directory layout

### ISSUE THREAD

**Issue by olt** [mapproxy/mapproxy#257]
> The algorithm used by S3 to partition and optimize buckets doesn't work well with hierarchical naming schemes as TMS.

The hierarchical `directory_layouts` can hit limitations of S3 *"if you are routinely processing 100 or more requests per second"*. See: http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

A new y/x/z.png directory layout could work around this limitation. OpenLayers/Leaflet/etc. should handle this as well (when accessing S3 directly) with URL templates.

**Comment by olt** [comment]
@panchicore do you need this for hypermap?

**Comment by panchicore** [comment]
If need it or not, let me ask Ariel, but it's always a good idea in order to optimize s3 costs. As we plan use minio.io I don't know if the same limitations apply, I believe yes because the way it queries the storage backend, no matter what it be, it's with multiples request per sec, and I believe not, because if those file were served via webserver it wasn't a problem.

**Comment by ingenieroariel** [comment]
I am +1 on this feature too as  we need this too to simplify direct access to the cache from the OL3 client.

**Comment by olt** [comment]
Added with 776bbad564a26ced49455c8d94c9b1b75eac2158.
