### ISSUE TITLE
Does MapProxy support serving over HTTPS? Can't see in documentation.

### ISSUE THREAD

**Issue by Dave6954** [mapproxy/mapproxy#448]
Does MapProxy support serving over HTTPS? Can't see in documentation.

**Comment by brian32768** [comment]
I run behind a nginx proxy for https and it works fine that way.

**Comment by Dave6954** [comment]
Hi Brian,

That's really interesting, so are you running a production map proxy on Ubuntu and Apache with Nginx in front as a reverse proxy? Are there decent build notes out there for such a solution?

Best regards,

David

Best Regards,

David Brooks
Director

T +44 7817 144305
E summitgeo@outlook.com
Summit Geo Ltd.


________________________________

**Comment by brian32768** [comment]
I used docker-compose. 

The one for mapproxy is here https://github.com/Wildsong/docker-mapproxy 
and the nginx + Let's Encrypt one is here https://github.com/Wildsong/docker-proxy

There are some comments at the end of docker-proxy README.md that talk about logging and I am pretty sure I removed that from the code. 

With mapproxy I am using couchdb as the backend tile store, so docker-mapproxy starts those two containers, mapproxy in waitress and couchdb. I also use raster tile packages generated in ArcGIS Pro and put them into mapproxy in the ESRI "compact v2" format. Works great.

"docker-proxy" uses two projects that already existed, one runs nginx and the other manages Let's Encrypt certs. I just built the docker-compose for them. It's a separate project because I use it for several other services unrelated to GIS.

You can hit our server at https://giscache.co.clatsop.or.us/ and see it. It all works great for us. Clatsop County is small, so all I can say about performance etc is running it this way works fine for "small". Everything runs in one Debian virtual machine.

**Comment by weskamm** [comment]
Closing as question has been answered
